### ISSUE TITLE
Websocket hostname in development.ini

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#10]
It seems that changing the following development.ini line would be a good idea (although I guess I'm running into this because I'm fiddling with the development environment with a server setup):

```
changes.websocket.url = http://localhost:%(changes.websocket.port)s%(changes.prefix)s/
```

into:

```
changes.websocket.url = http://%(public_hostname):%(changes.websocket.port)s%(changes.prefix)s/
```

Also does making this change in development.ini require an app_compile?

**Comment by jmatsushita** [comment]
Looks like I can't restart anymore with that change. Supervisord doesn't give me a useful log. I've hardwired the IP I'm using and it's working again.

**Comment by maparent** [comment]
If the public hostname is not visible from the host, the websocket url will fail.
If you're doing nginx etc. you'll want to start from a production.ini file.

**Comment by maparent** [comment]
More on ini files: We usually copy `production.ini` to a `local.ini` file, which we can modify with appropriate values. The `fab env_dev <subcommand>` will pick that up instead of `development.ini`.
Some changes just require an application reload, some require an app_compile, especially anything having to do with ports and hostnames.
